---

max_packets_in_flow: 30
partitions: 1024
mask_ip: yes
mask_port: yes

labels:
  - "AIMchat"
  - "aim_chat"
  - "email"
  - "facebook_audio"
  - "facebookchat"
  - "facebook_chat"
  - "facebook_video"
  - "ftps_down"
  - "ftps_up"
  - "gmailchat"
  - "hangout_chat"
  - "hangouts_audio"
  - "hangouts_chat"
  - "hangouts_video"
  - "ICQchat"
  - "icq_chat"
  - "netflix"
  - "scp"
  - "scpDown"
  - "scpUp"
  - "sftp"
  - "sftpDown"
  - "sftp_down"
  - "sftpUp"
  - "sftp_up"
  - "skype_audio"
  - "skype_chat"
  - "skype_file"
  - "skype_video"
  - "spotify"
  - "torFacebook"
  - "torGoogle"
  - "Torrent"
  - "torTwitter"
  - "torVimeo"
  - "torYoutube"
  - "vimeo"
  - "voipbuster"
  - "vpn_aim_chat"
  - "vpn_bittorrent"
  - "vpn_email"
  - "vpn_facebook_audio"
  - "vpn_facebook_chat"
  - "vpn_ftps"
  - "vpn_hangouts_audio"
  - "vpn_hangouts_chat"
  - "vpn_icq_chat"
  - "vpn_netflix"
  - "vpn_sftp"
  - "vpn_skype_audio"
  - "vpn_skype_chat"
  - "vpn_skype_files"
  - "vpn_spotify"
  - "vpn_vimeo"
  - "vpn_voipbuster"
  - "vpn_youtube"
  - "youtube"
  - "youtubeHTML"

#labels:
#  - "Aliexpress.com"
#  - "Alipay.com"
#  - "Amazon.co"
## - "Amazon.co.jp"
## - "Amazon.com"
#  - "Baidu.com"
#  - "Bilibili.com"
#  - "Bing.com"
#  - "Blogspot.com"
#  - "Csdn.net"
#  - "Ebay.com"
#  - "Facebook.com"
#  - "Github.com"
#  - "Google.co"
## - "Google.co.in"
## - "Google.com.hk"
## - "Google.com"
#  - "Imdb.com"
#  - "Instagram.com"
#  - "Jd.com"
#  - "Linkedin.com"
#  - "Live.com"
#  - "Livejasmin.com"
#  - "Login.tmall.com"
#  - "Mail.ru"
#  - "Microsoft.com"
#  - "Microsoftonline.com"
#  - "Netflix.com"
#  - "Office.com"
#  - "Pages.tmall.com"
#  - "porn.com"
#  - "Pornhub.com"
#  - "Qq.com"
#  - "Reddit.com"
#  - "Sina.com.cn"
#  - "Sohu.com"
#  - "Stackoverflow.com"
#  - "Taobao.com"
#  - "T.co"
#  - "Tmall.com"
#  - "Tribunnews.com"
#  - "Twitch.tv"
#  - "Twitter.com"
#  - "uwaterloo.ca"
#  - "Weibo.com"
#  - "Wikipedia.org"
#  - "Xvideos.com"
#  - "Yahoo.co"
## - "Yahoo.co.jp"
## - "Yahoo.com"
#  - "Yandex.ru"
#  - "Youtube.com"
